run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/justyntemme/vst3go
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/justyntemme/vst3go

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar    # replaces exportloopref (Go 1.22+)
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd            # replaces gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive         # replaces golint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused         # replaces deadcode, structcheck, varcheck
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-dirs:
    - build
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
    # C bindings have different naming conventions
    - path: pkg/vst3/
      linters:
        - revive
        - stylecheck
    - path: bridge/
      linters:
        - revive
        - stylecheck
    # Wrapper files interface with C code
    - path: pkg/plugin/wrapper.*\.go
      linters:
        - revive
        - stylecheck
        - funlen
    # Examples can have longer functions for clarity
    - path: examples/
      linters:
        - funlen
        - gocyclo
    # DSP packages use mathematical constants
    - path: pkg/dsp/
      linters:
        - mnd
    # Bus configuration has expected channel counts
    - path: pkg/framework/bus/
      linters:
        - mnd
    # VST3 bindings have long C function signatures and binary constants
    - path: pkg/vst3/
      linters:
        - lll
        - mnd
    # Plugin package deals with C interop and has some necessary duplication
    - path: pkg/plugin/
      linters:
        - dupl
        - lll
        - mnd
        - revive  # C interface functions often have unused parameters
        - gocritic  # C binding patterns don't follow Go conventions
        - gocyclo  # Complex C interop functions
        - staticcheck  # Empty branches are placeholders for future C implementations
        - govet  # Unsafe operations are necessary for C interop
    # Parameter formatters have conversion constants and necessary unsafe operations
    - path: pkg/framework/param/
      linters:
        - mnd
        - gosec  # Uses necessary unsafe operations for atomic values

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0